### ISSUE TITLE
Will this library be only limited to Linux / *Nix?

### ISSUE THREAD

**Issue by neeraj9** [msantos/alcove#2]
There is a huge potential for using this library in [beamparticle](https://github.com/beamparticle/beamparticle), but unfortunately, it does not support Mac OS X. This results in https://github.com/beamparticle/beamparticle/issues/46

Summary: Is this library not meant to support Mac OS X?

**Comment by msantos** [comment]
Hey @neeraj9 ! beamparticle looks very interesting, I've added it to my list of projects to check out!

Mac OS X is definitely on the list of OS'es alcove should support.  I don't think I've ever tested though. I have a patch that I think should fix the errors in https://github.com/beamparticle/beamparticle/issues/46 , just setting up a mac os x system to test on.

**Comment by neeraj9** [comment]
@msantos This is awesome!
The documentation is non-existent due to lack of time. Do let me know if you have any questions although building it on Linux should just work (I test it regularly on Ubuntu 16.04). I chose alcove due to its architecture and opening up amazing possibility of a very lightweight containerization.

**Comment by msantos** [comment]
Working on Mac OS X now. And thanks for the pointer to beamparticle, I'm reading through the source now.

Let me know if you run into any other issues!
